### ISSUE TITLE
The `Roman` type should use `NonZeroU16` instead of `i32`

### ISSUE THREAD

**Issue by WaffleLapkin** [archer884/xvii#8]
- `Roman` is meaningless with negative numbers, so it's reasonable to use unsigned integer
- `Roman` is meaningless with `0`, so it's reasonable to use `NonZero*`
- `u16::MAX >= 4999`

**Comment by archer884** [comment]
Reasonable, but annoying. Is there any benefit to doing this? =)

I ask particularly in light of the following logic, which requires that the integer in question be able to represent zero:
```rust
/// Formats a `Roman` value as a lowercase Roman numeral.
pub fn to_lowercase(self) -> String {
    let mut current = self.0;
    let mut buf = String::new();
    for &(unit, value) in ladder::LOWER.iter() {
        while current >= value {
            buf.push_str(unit);
            current -= value;
        }
    }
    buf
}
```
I mean, I am assuming that a conversion from a non-zero integer to a normal one is extremely cheap, but it does mean an extra step in code, and since the calculation itself would be performed using an ordinary integer, I'm wondering what difference it would make.

**Comment by WaffleLapkin** [comment]
> Is there any benefit to doing this

I think there are 2 benefits:
- Less representable illegal states (this also makes the code more self-explanatory)
- Less space taken, e.g.
  ```
  [src/main.rs:5] size_of::<i32>() = 4
  [src/main.rs:6] size_of::<Option<i32>>() = 8
  [src/main.rs:7] size_of::<u16>() = 2
  [src/main.rs:8] size_of::<Option<u16>>() = 4
  [src/main.rs:9] size_of::<NonZeroU16>() = 2
  [src/main.rs:10] size_of::<Option<NonZeroU16>>() = 2
  ```
  ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=03075cf7940e3acdea1cfff099166b09))

If you're ok with this change, I can make a pr :)

**Comment by archer884** [comment]
Sure. I'm curious to see what you'd come up with. Just a heads up, I updated the code for 2018 while I was poking around in it this morning, so you'll want to pull the latest before you start modifying things.
